### ISSUE TITLE
Solution for round1-om-0250-breaking-all-the-rulez is incorrect

### ISSUE THREAD

**Issue by chrisreljin** [cisagov/prescup19-challenges#2]
# 🐛 Bug Report

After attempting the challenge, I reviewed the solution to validate my results. However, the provided solution does not match any of the provided filenames.

## To Reproduce

**Review filenames here ->** https://github.com/cisagov/prescup19-challenges/tree/master/individual/round1-om-0250-breaking-all-the-rulez/challenge

**Filenames for clarity:**
1. Ruleset-86evewzu0sas
2. Ruleset-9p5zxdq2ld79
3. Ruleset-j1wk1w4er1qf
4. Ruleset-k6wuzqsrs8a0
5. Ruleset-mcf110q4so2n
6. Ruleset-mw3btxj1ndrq
7. Ruleset-tyw4z7d8ohsj
8. Ruleset-vfb1lypfkhie
9. Ruleset-yk00o2k5vv26
10. Ruleset-z1tqg6mtu5nw

**Provided solution:** The correct choice for the version in this repository is `Ruleset-zs54sjfnlub7`.

**Comment by hcm004** [comment]
Thanks for bringing this to our attention! We have several variants to each challenge, and the solution was from a different challenge variant. We've pushed the correction, so the solution should now be correct.

Thank you for submitting this bug report, and please feel free to submit more for any issues you identify!
